#[programs.mainnet]
#laddercast = "LCNTy2Q4HsKUecKEETwwzujjbAx9DGFJort8SjGzGFj"
#[programs.devnet]
#laddercast = "LCThBz55Ma7hcueUQA3iiofBhvidQHfNLxxwfLsycxb"
[programs.localnet]
laddercast = "Aejjj86wGd3B4BEEaQyn4663xabWxLyNkJr6d7qLRcov"

[registry]
url = "https://anchor.projectserum.com"

[provider]
#cluster = "mainnet"
#wallet = "~/.config/solana/prod/game-deploy.json"
#cluster = "devnet"
#wallet = "~/.config/solana/id.json"
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
dep = "bash ./migrations/deploy.sh"